# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
yarn_mappings=1.21.1+build.3

# Mod Properties
version=0.1.0
group=com.example.ainarrator

# Dependencies
fabric_api_version=0.103.0+1.21.1
